export const filterOptions = {
  page: "number",
  limit: "number",
  order: ["relevance", "recent"],
  term: "string",
  filters: {
    orientation: ["landscape", "portrait", "square", "panoramic"],
    content_type: ["photo", "vector", "psd"],
    license: ["freemium", "premium"],
    people: {
      include: "number",
      exclude: "number",
      number: ["1", "2", "3", "more_than_three"],
      age: [
        "infant",
        "child",
        "teen",
        "young-adult",
        "adult",
        "senior",
        "elder",
      ],
      gender: ["male", "female"],
      ethnicity: [
        "south-asian",
        "middle-eastern",
        "east-asian",
        "black",
        "hispanic",
        "indian",
        "white",
        "multiracial",
      ],
    },
    period: ["last-month", "last-quarter", "last-semester", "last-year"],
    color: [
      "black",
      "blue",
      "gray",
      "green",
      "orange",
      "red",
      "white",
      "yellow",
      "purple",
      "cyan",
      "pink",
    ],
    author: "number",
    ai_generated: {
      excluded: "number",
      only: "number",
    },
    vector: {
      type: ["jpg", "ai", "eps", "svg"],
      style: [
        "watercolor",
        "flat",
        "cartoon",
        "geometric",
        "gradient",
        "isometric",
        "3d",
        "hand-drawn",
      ],
    },
    psd: {
      type: ["jpg", "psd"],
    },
    ids: "string",
  },
};
